"""add zoning column to parcels

Revision ID: 5ba580ecaa4b
Revises: 802fb5f3b79b
Create Date: 2026-08-25 20:43:26.120581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ba580ecaa4b'
down_revision: Union[str, Sequence[str], None] = '802fb5f3b79b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parcels', sa.Column('zoning', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parcels', 'zoning')
    # ### end Alembic commands ###
