"""add upi geometry and area to parcels

Revision ID: 802fb5f3b79b
Revises: 4b0c13b39893
Create Date: 2026-08-25 20:08:03.302337

"""
from typing import Sequence, Union

import geoalchemy2
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '802fb5f3b79b'
down_revision: Union[str, Sequence[str], None] = '4b0c13b39893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parcels', sa.Column('upi', sa.String(length=100), nullable=False))
    op.add_column('parcels', sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False))
    op.add_column('parcels', sa.Column('area_m2', sa.Float(), nullable=True))
    op.create_index(op.f('ix_parcels_upi'), 'parcels', ['upi'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parcels_upi'), table_name='parcels')
    op.drop_column('parcels', 'area_m2')
    op.drop_column('parcels', 'geometry')
    op.drop_column('parcels', 'upi')
    # ### end Alembic commands ###
